permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: pygments
markdown: kramdown

title : Chris Peak
author : "Chris Peak"
name : "Chris"
email : cpeak66@gmail.com
github : cpeak
twitter : c_peak
feedburner :

production_url : http://cpeak.github.io
