permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
highlighter: true
markdown: kramdown

title : Design + Code
author : "Chris Peak"
name : "Chris"
email : chris@8thlight.com
github : cpeak
twitter : c_peak
feedburner :

production_url : http://cpeak.github.io
sass:
  sass_dir: /css/_sass
